name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            folder: linux
          - os: macos-latest
            folder: macos
          - os: windows-latest
            folder: windows
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py
          mkdir -p dist/${{ matrix.folder }}
          mv dist/main* dist/${{ matrix.folder }}/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.folder }}
          path: dist/${{ matrix.folder }}/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_PREFIX: v
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          files: |
            dist/linux/*
            dist/macos/*
            dist/windows/*