name: Release on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          files: |
            dist/linux/*
            dist/macos/*
            dist/windows/*